### ISSUE TITLE
App crash when deleting item

### ISSUE THREAD

**Issue by Dostoi** [dsoulayrol/android-sholi#18]
When there is only one item and you're deleting it, the app crash every time.
It happens too when there is multiple items but not all the time.

version1.4.2 on a wiko cink peax with android 4.1.2

**Comment by dsoulayrol** [comment]
I can confirm the behaviour.

**Comment by slumdroid** [comment]
This is the stacktrace:

E/AndroidRuntime(  905): FATAL EXCEPTION: main
E/AndroidRuntime(  905): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
E/AndroidRuntime(  905): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
E/AndroidRuntime(  905): 	at java.util.ArrayList.get(ArrayList.java:304)
E/AndroidRuntime(  905): 	at de.greenrobot.dao.query.LazyList.get(LazyList.java:233)
E/AndroidRuntime(  905): 	at name.soulayrol.rhaa.sholi.data.AbstractLazyListAdapter.getItemId(AbstractLazyListAdapter.java:81)
E/AndroidRuntime(  905): 	at android.widget.AbsListView.confirmCheckedPositionsById(AbsListView.java:5288)
E/AndroidRuntime(  905): 	at android.widget.AbsListView.handleDataChanged(AbsListView.java:5331)
E/AndroidRuntime(  905): 	at android.widget.ListView.layoutChildren(ListView.java:1528)
E/AndroidRuntime(  905): 	at android.widget.AbsListView.onLayout(AbsListView.java:2102)
E/AndroidRuntime(  905): 	at android.widget.AdapterView.updateEmptyStatus(AdapterView.java:747)
E/AndroidRuntime(  905): 	at android.widget.AdapterView.checkFocus(AdapterView.java:720)
E/AndroidRuntime(  905): 	at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:812)
E/AndroidRuntime(  905): 	at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6044)
E/AndroidRuntime(  905): 	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
E/AndroidRuntime(  905): 	at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
E/AndroidRuntime(  905): 	at name.soulayrol.rhaa.sholi.data.AbstractLazyListAdapter.setLazyList(AbstractLazyListAdapter.java:49)
E/AndroidRuntime(  905): 	at name.soulayrol.rhaa.sholi.EditFragment$SelectionModeHandler.onActionItemClicked(EditFragment.java:202)
E/AndroidRuntime(  905): 	at android.widget.AbsListView$MultiChoiceModeWrapper.onActionItemClicked(AbsListView.java:6100)
E/AndroidRuntime(  905): 	at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onActionItemClicked(PhoneWindow.java:2530)
E/AndroidRuntime(  905): 	at com.android.internal.app.ActionBarImpl$ActionModeImpl.onMenuItemSelected(ActionBarImpl.java:931)
E/AndroidRuntime(  905): 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
E/AndroidRuntime(  905): 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
E/AndroidRuntime(  905): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
E/AndroidRuntime(  905): 	at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:514)
E/AndroidRuntime(  905): 	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:99)
E/AndroidRuntime(  905): 	at android.view.View.performClick(View.java:4084)
E/AndroidRuntime(  905): 	at android.view.View$PerformClick.run(View.java:16966)
E/AndroidRuntime(  905): 	at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime(  905): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(  905): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(  905): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime(  905): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  905): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(  905): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime(  905): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime(  905): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  271):   Force finishing activity name.soulayrol.rhaa.sholi/.MainActivity
