### ISSUE TITLE
Crossing / removing items does not mark them on server

### ISSUE THREAD

**Issue by Yyuzu** [dsoulayrol/android-sholi#22]
Hi,

Whenever I click on an item, it gets crossed in the app, but no query is sent to the server. When I close the app and come back nothing gets crossed / deleted. Is it normal ?

I'm using the app from F-Droid v1.3 (4) with the backend on my server (master branch).

Thank you for the app :-)
Regards

**Comment by dsoulayrol** [comment]
Hi.

I am sorry I does not understand what is your problem. Where did you find a server was implied in Sholi usage?

**Comment by Yyuzu** [comment]
My bad, I must have the wrong project.
