### ISSUE TITLE
Add import capabilities

### ISSUE THREAD

**Issue by strk** [dsoulayrol/android-sholi#24]
Sending a shopping list to someone is currently supported and results in the other party getting a text-formatted list as a result. It would be useful for the other party to be able to _import_ the text-formatted list into the local database, ideally skipping duplicates (with some fuzzyness)

**Comment by strk** [comment]
Oops, I just figured out it's already supported. Sorry for the noise (sholi registers self as a share-to target)

**Comment by strk** [comment]
Thanks a lot for this @dsoulayrol  :)

**Comment by dsoulayrol** [comment]
You're welcome!
